export const ACTIONS = {
    SET_SELECTED_TAB: "SET_SELECTED_TAB",
    SET_DROPDOWN_VALUE: "SET_DROPDOWN_VALUE",
    SET_SEARCH_VALUE: "SET_SEARCH_VALUE",
    RESET_EXPORT_DATA: "RESET_EXPORT_DATA",
};
